### ISSUE TITLE
[Question] Matrix room

### ISSUE THREAD

**Issue by Jiack214** [Limvot/Chatatat#1]
Hi! Is there a matrix room to talk about this app's development?

**Comment by Limvot** [comment]
Hi! There wasn't yet - I started the project a week ago and didn't expect interest so quickly, but I just made one: #chatatat:room409.xyz, or the matrix.to link https://matrix.to/#/!vvCKJZzuezMbbgfJrW:room409.xyz?via=room409.xyz&via=matrix.org

Thanks for your interest, and please feel free to ask any questions!
